---
# 排序权重(可选):数字越小,在主页菜单中越靠前
weight: 20

# Page meta info, like heading, footer text and nav links
pageInfo:
  logo: /favicon-trend.ico
  title: nav
  description: A lightweight self-hostable personal dashboard
  footerText: (╹ڡ╹ )

# Main content - An array of sections, each containing an array of items
sections:
  - name: Github 趋势
    icon: fa fa-github
    items:
      - title: OssInsight
        description: The comprehensive Open Source Software insight tool by analyzing massive events from GitHub, powered by TiDB, the best insight building database of data agility.
        icon: https://ossinsight.io/img/favicon-1.png
        url: https://ossinsight.io/
