---
# Page meta info, like heading, footer text and nav links
pageInfo:
  logo: /favicon.ico
  title: moshi
  description: A lightweight self-hostable personal dashboard
  navLinks:
    - title: GitHub
      path: https://github.com/rowink/moshi
  footerText: (ﾉ´ヮ´)ﾉ*:･ﾟ✧

# Optional app settings and configuration
appConfig:
  language: cn
  statusCheck: true
  statusCheckInterval: 0
  defaultOpeningMethod: modal

# Main content - An array of sections, each containing an array of items
sections:
  - name: 强化搜索
    icon: fas fa-search
    items:
      - title: Saveweb Search
        description: A full- search engine for blog posts
        icon: https://search.save-web.org/neosearch.svg
        url: https://search.saveweb.org/
      - title: ImageDash
        description: Reverse search with an image, URL, or text to find what you're looking for across the web's top image search engines.
        icon: https://image-dash.itea.dev/favicon.ico
        url: https://image-dash.itea.dev/

  - name: 来源标记
    icon: fa fa-location-arrow
    items:
      - title: IP.orz.tools
        description: What's My IP?
        icon: https://ip.orz.tools/assets/favicon.17e50649.svg
        url: https://ip.orz.tools/
      - title: dnscheck.tools
        description: A tool to test for DNS leaks, DNSSEC validation, and more
        icon: https://dnscheck.tools/favicon.svg
        url: https://dnscheck.tools/
