---
# Page meta info, like heading, footer text and nav links
pageInfo:
  logo: /favicon.ico
  title: moshi
  description: A lightweight self-hostable personal dashboard
  navLinks:
    - title: GitHub
      path: https://github.com/rowink/moshi
  footerText: (ﾉ´ヮ´)ﾉ*:･ﾟ✧

# Optional app settings and configuration
appConfig:
  language: cn
  statusCheck: true
  statusCheckInterval: 0
  defaultOpeningMethod: modal

# Main content - An array of sections, each containing an array of items
sections:
  - name: 项目
    icon: fas fa-book
    items:
      - title: Iris Analytics
        description: A lightweight, open-source website analytics dashboard powered by Cloudflare Pages + Analytics Engine
        icon: https://iris.exi.software/favicon.ico
        url: https://iris.exi.software/
      - title: cc0-sounds
        description: Free CC0 Sound Effects Library - Browse and download royalty-free audio files
        icon: https://cc0-sounds.exi.software/favicon.svg
        url: https://cc0-sounds.exi.software/
